src/BK.UserManagement.Web/Controllers/PrivilegeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BK.UserManagement.Web.Models;
using Oracle.ManagedDataAccess.Client;
using Microsoft.Extensions.Configuration;
using Dapper;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BK.UserManagement.Web.Controllers
{
    public class PrivilegeController : Controller
    {

        private readonly IConfiguration config;
        private string connString;

        public PrivilegeController(IConfiguration iconfig)
        {
            config = iconfig;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GrantSysPrivs(string id)
        {
            using (var ole = new OracleConnection(config.GetConnectionString("DefaultConnection")))
            {

                //var listPriv = ole.Query($"select * from SESSION_PRIVS");
                //var sl = listPriv.Select(x =>
                //                    new SelectListItem()
                //                    {
                //                        Text = x.PRIVILEGE.ToString(),
                //                        Value = x.PRIVILEGE.ToString()
                //                    });
                //ViewBag.ListPriv = sl.ToList();


                 ViewBag.ListPriv = new SelectList(new[] { "CREATE PROFILE", "ALTER PROFILE", "DROP PROFILE", "CREATE ROLE", "ALTER ANY ROLE", "DROP ANY ROLE", "GRANT ANY ROLE", "CREATE SESSION"
                 , "CREATE ANY TABLE", "ALTER ANY TABLE", "DROP ANY TABLE", "SELECT ANY TABLE", "DELETE ANY TABLE", "INSERT ANY TABLE", "UPDATE ANY TABLE", "CREATE TABLE", "CREATE USER", "ALTER USER", "DROP USER" }, "");
                ViewBag.ListAdmin = new SelectList(new[] { "YES", "NO"}, "YES");
                ViewBag.ListType = new SelectList(new[] { "GRANT", "REVOKE" }, "GRANT");
                ViewBag.Username = id;
                var listSysPriv = ole.Query<SysPrivsModel>($"select * from sys.DBA_SYS_PRIVS WHERE GRANTEE = '{id}'");
                return View(listSysPriv);
            }

        }


        [HttpPost]
        public IActionResult GrantSysPrivs(string _username,string ListPriv,string ListAdmin,string ListType)
        {
            using (var ole = new OracleConnection(config.GetConnectionString("DefaultConnection")))
            {
                if (ListType == "GRANT")
                {

                    var iExist = ole.Query($@"SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = '{_username}' AND PRIVILEGE LIKE '{ListPriv}%'").Count();
                    if (iExist > 0)
                    {
                        ole.Query<string>($@"REVOKE {ListPriv} FROM {_username}");
                    }

                    
                    //ole.Query<string>($@"REVOKE {ListPriv} FROM {_username}");

                    if (ListAdmin == "YES")
                    {
                        ole.Query<string>($@"{ListType} {ListPriv} TO {_username} WITH ADMIN OPTION");
                    }
                    else
                    {
                        ole.Query<string>($@"{ListType} {ListPriv} TO {_username}");
                    }
                    
                }
                else if(ListType == "REVOKE")
                {
                    var iExist = ole.Query($@"SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = '{_username}' AND PRIVILEGE LIKE '{ListPriv}%'").Count();
                    if (iExist > 0)
                    {
                        ole.Query<string>($@"{ListType} {ListPriv} FROM {_username}");
                    }

                    
                }
                

                return RedirectToAction("GrantSysPrivs",new { id = _username });
            }

        }


    }
}

src/BK.UserManagement.Web/Views/Privilege/GrantSysPrivs.cshtml
@using BK.UserManagement.Web.Models
@model IEnumerable<SysPrivsModel>
@{
    ViewData["Title"] = "Grant Sys Privileges To User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Grant System Privileges To @ViewBag.Username
    </h1>

    @*<ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> User</a></li>
        <li class="active">Edit</li>
    </ol>*@
</section>

<section class="content">
    <div class="row">
        <div class=" col-md-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    @using (Html.BeginForm("GrantSysPrivs", "Privilege")) { 
                    <div class="form-group">
                        <INPUT TYPE="text" NAME="_username" value="@ViewBag.Username" style="display: none">
                        <label class="col-md-1 control-label">PRIVILEGE</label>
                        <div class="col-md-11">
                            @Html.DropDownList("ListPriv", null, null, htmlAttributes: new { @class = "form-control select2" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label">ADMIN_OPTION</label>
                        <div class="col-md-11">
                            @Html.DropDownList("ListAdmin", null, null, htmlAttributes: new { @class = "form-control select2" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label">ACTION</label>
                        <div class="col-md-11">
                            @Html.DropDownList("ListType", null, null, htmlAttributes: new { @class = "form-control select2" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <button type="submit"
                                    class="btnSave btn btn-success pull-left" style="margin-right: 5px;">
                                <i class="fa fa-save"></i> Save
                            </button>
                        </div>
                    </div>
                    }
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    @if (ViewBag.Message != null)
                    {
                        <div class="alert alert-warning alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button>
                            <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                            @ViewBag.Message
                        </div>
                    }
                    <table id="tbl_userSysPriv" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>PRIVILEGE</th>
                                <th>ADMIN_OPTION</th>

                            </tr>
                        </thead>
                        <tbody>



                            @foreach (var u in Model)
                            {
                                <tr>
                                    <td>@u.PRIVILEGE</td>
                                    <td>@u.ADMIN_OPTION</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</section>
@section Scripts {
<script type="text/javascript">
        $(document).ready(function () {

            $('.select2').select2();

        });
</script>
}